"use client";
import { useEffect, useState, type ReactNode } from "react";
import { ActionButton, CheckboxField, StatusBadge, TextField } from "../components/ui";
import { FocusPopover, WidgetDialog, WidgetDivider, WidgetGroup } from "../components/ui/Widgets";
import { WidgetsIcon } from "../components/ui/Icons";
import "./widgets-section.css";

function Demo({number,title,description,children}:{number:string;title:string;description:string;children:ReactNode}){return <section className="ds-widget-demo"><header><span className="ds-widget-index">{number}</span><h2>{title}</h2><p>{description}</p></header><div className="ds-widget-demo__stage">{children}</div></section>}
export function WidgetsSection() {
 const [overlay,setOverlay]=useState<"modal"|"drawer"|"sheet"|null>(null),[onlyActive,setOnlyActive]=useState(true),[surface,setSurface]=useState<"card"|"outline"|"plain">('card'),[sheetChoice,setSheetChoice]=useState(true),[preview,setPreview]=useState(true);
 const close=()=>setOverlay(null);
 useEffect(()=>{const media=matchMedia("(max-width:680px)");const update=()=>{if(!media.matches)setOverlay(current=>current==="sheet"?null:current)};media.addEventListener("change",update);return()=>media.removeEventListener("change",update)},[]);
 return <section className="ds-widgets" aria-labelledby="widgets-title"><header className="ds-widgets-intro"><span className="ds-widget-emblem"><WidgetsIcon size={26}/></span><div><span className="ds-kicker">Composição da interface</span><h1 id="widgets-title">Widgets</h1><p>Organize o conteúdo, crie respiro e revele os detalhes no momento certo.</p></div></header>
 <Demo number="01" title="Superfícies e grupos" description="Um mesmo conteúdo pode ganhar diferentes níveis de destaque. Compare o cartão, o contorno e o grupo aberto."><div className="ds-widget-switch" role="group" aria-label="Tipo de superfície">{([['card','Cartão'],['outline','Contorno'],['plain','Aberto']] as const).map(([value,label])=><ActionButton key={value} variant="quiet" aria-pressed={surface===value} onClick={()=>setSurface(value)}>{label}</ActionButton>)}</div><div className="ds-widget-canvas"><WidgetGroup variant={surface}><StatusBadge tone="info">Visão geral</StatusBadge><h3>Processo de seleção</h3><p>Reúna informações relacionadas dentro do mesmo grupo.</p><WidgetDivider/><div className="ds-widget-inline"><span>Vagas em andamento</span><strong>12</strong></div></WidgetGroup></div><p className="ds-widget-caption ds-widget-footnote">{surface==='card'?'Fundo e borda para resumos, formulários e blocos principais.':surface==='outline'?'Contorno para delimitar um grupo sem criar uma nova camada de fundo.':'Espaço em branco para relacionar itens sem adicionar bordas.'}</p></Demo>
 <Demo number="02" title="Coleções de cartões" description="A mesma hierarquia, alinhamento e distância entre itens. No celular, os cartões se organizam em uma coluna."><div className="ds-widget-grid">{[['Vagas abertas','12'],['Em entrevista','28'],['Contratações','4']].map(([label,value])=><WidgetGroup key={label}><span>{label}</span><strong className="ds-widget-number">{value}</strong><span className="ds-widget-caption">Exemplo de indicador</span></WidgetGroup>)}</div></Demo>
 <Demo number="03" title="Espaço para respirar" description="A proximidade mostra o que pertence ao mesmo assunto. Um intervalo maior ou uma divisória sinaliza uma nova seção."><div className="ds-widget-spacing">{[8,16,24,32].map(n=><div key={n}><div className="ds-widget-space-sample"><i style={{width:n,height:n}}/></div><strong>{n} px</strong><span>{n===8?'Itens próximos':n===16?'Entre controles':n===24?'Dentro do grupo':'Entre seções'}</span></div>)}</div><WidgetDivider label="Mudança de assunto"/><p className="ds-widget-caption">Prefira espaço em branco dentro do mesmo grupo. Use divisórias entre conjuntos distintos.</p></Demo>
 <Demo number="04" title="Detalhes e ações" description="Escolha o formato pelo contexto: uma decisão breve, opções junto ao botão ou informações em um painel lateral."><div className="ds-overlay-examples"><WidgetGroup><span className="ds-widget-caption">POP-UP</span><h3>Uma ação por vez</h3><p>Para confirmações e formulários curtos.</p><ActionButton onClick={()=>setOverlay('modal')}>Experimentar pop-up</ActionButton></WidgetGroup><WidgetGroup><span className="ds-widget-caption">GROUP FOCUS</span><h3>Opções no contexto</h3><p>Um grupo compacto ancorado ao controle.</p><FocusPopover label="Ajustar visualização"><strong>Preferências da lista</strong><CheckboxField label="Somente vagas ativas" checked={onlyActive} onChange={e=>setOnlyActive(e.target.checked)}/></FocusPopover></WidgetGroup><WidgetGroup className="ds-widget-drawer-demo"><div><span className="ds-widget-caption">PAINEL LATERAL DIREITO</span><h3>Explore sem sair da página</h3><p>Detalhes com rolagem própria e fechamento sempre acessível.</p></div><ActionButton variant="secondary" onClick={()=>setOverlay('drawer')}>Abrir painel lateral</ActionButton></WidgetGroup></div></Demo>
 <Demo number="05" title="BottomSheet mobile" description="Um painel que surge pela base da tela. Arraste a alça para baixo, toque fora ou use Fechar para retornar à página."><div className="ds-sheet-layout"><div className="ds-sheet-guide"><h3>Próximo às mãos</h3><p>Conteúdo com rolagem interna, ações acessíveis e espaço reservado para a área segura do celular.</p><ActionButton className="ds-sheet-mobile-trigger" onClick={()=>setOverlay('sheet')}>Experimentar no celular</ActionButton><ActionButton className="ds-sheet-desktop-trigger" variant="secondary" onClick={()=>setPreview(v=>!v)}>{preview?'Recolher prévia':'Abrir prévia'}</ActionButton><span className="ds-widget-caption">No desktop, a demonstração fica dentro da moldura.</span></div><div className="ds-sheet-preview" aria-label="Demonstração do BottomSheet em uma tela de celular"><div className="ds-sheet-preview__context"><span>Prévia mobile</span><strong>Vagas da empresa</strong><div/><div/><ActionButton variant="quiet" onClick={()=>setPreview(true)}>Opções de visualização</ActionButton></div><div className={`ds-sheet-preview__surface ${preview?'is-open':''}`} inert={!preview||undefined} aria-hidden={!preview}><button className="jf-sheet-grip" aria-label="Recolher prévia" onClick={()=>setPreview(false)}><span className="jf-sheet-handle"/></button><h3>Visualização da lista</h3><p>Mostre o que é relevante para você.</p><CheckboxField label="Somente vagas ativas" checked={sheetChoice} onChange={e=>setSheetChoice(e.target.checked)}/><ActionButton onClick={()=>setPreview(false)}>Aplicar na prévia</ActionButton></div></div></div></Demo>
 <WidgetDialog open={overlay==='modal'} onClose={close} title="Salvar preferências" description="Uma ação breve sem perder o contexto." footer={<><ActionButton variant="quiet" onClick={close}>Cancelar</ActionButton><ActionButton onClick={close}>Concluir exemplo</ActionButton></>}><TextField label="Nome da visualização" placeholder="Ex.: Vagas do time comercial"/><p className="ds-widget-caption">Demonstração visual. Nenhuma configuração será alterada.</p></WidgetDialog>
 <WidgetDialog open={overlay==='drawer'} onClose={close} kind="drawer" title="Detalhes da vaga" description="Informações adicionais no contexto da lista." footer={<ActionButton variant="secondary" onClick={close}>Fechar detalhes</ActionButton>}><StatusBadge tone="positive">Publicada</StatusBadge><h3>Analista de Customer Success</h3><p>Time de relacionamento · Híbrido</p><WidgetDivider label="Sobre a oportunidade"/><p>Acompanhe a experiência dos clientes, organize demandas e apoie o crescimento das contas.</p><WidgetGroup variant="outline"><strong>Próxima etapa</strong><p>Entrevista com a liderança.</p></WidgetGroup></WidgetDialog>
 <WidgetDialog open={overlay==='sheet'} onClose={close} kind="sheet" title="Visualização da lista" description="Escolha quais vagas deseja visualizar." footer={<ActionButton onClick={close}>Aplicar na demonstração</ActionButton>}><CheckboxField label="Somente vagas ativas" checked={sheetChoice} onChange={e=>setSheetChoice(e.target.checked)}/><p className="ds-widget-sheet-hint">Arraste a alça para baixo para fechar. Esta seleção altera apenas o exemplo.</p></WidgetDialog>
 </section>;
}
