"use client";
import { useEffect, useState } from "react";
import { ActionButton, CheckboxField, StatusBadge, TextField } from "../components/ui";
import { FocusPopover, WidgetDialog, WidgetDivider, WidgetGroup } from "../components/ui/Widgets";
import "./widgets-section.css";

export function WidgetsSection() {
 const [overlay,setOverlay]=useState<"modal"|"drawer"|"sheet"|null>(null),[onlyActive,setOnlyActive]=useState(true);
 const close=()=>setOverlay(null);
 useEffect(()=>{const media=matchMedia("(max-width:680px)");const update=()=>{if(!media.matches)setOverlay(current=>current==="sheet"?null:current)};media.addEventListener("change",update);return()=>media.removeEventListener("change",update)},[]);
 return <section className="ds-widgets" aria-labelledby="widgets-title"><header><span className="ds-kicker">Composição da interface</span><h1 id="widgets-title">Widgets</h1><p>Grupos organizam o conteúdo. Sobreposições dão espaço a uma ação ou aos detalhes, mantendo o contexto da página.</p></header>
 <section><h2>Grupos e containers</h2><p>Escolha a superfície pela importância do conteúdo. Preserve os mesmos espaçamentos, contornos e cores em todas as telas.</p><div className="ds-widget-grid">{([['card','Cartão','Agrupa um assunto com fundo e borda. Ideal para resumos e formulários.'],['outline','Somente contorno','Delimita conteúdo sem adicionar outra superfície à página.'],['plain','Grupo aberto','Organiza itens pela proximidade e pelo espaço, sem uma caixa adicional.']] as const).map(([variant,title,description])=><article key={variant}><WidgetGroup variant={variant}><StatusBadge tone="info">Exemplo</StatusBadge><h3>{title}</h3><p>{description}</p><WidgetDivider/><span className="ds-widget-caption">Espaço interno: 24 px · conteúdo relacionado: 8–16 px</span></WidgetGroup></article>)}</div></section>
 <section><h2>Grupos de cartões</h2><p>Cartões relacionados têm a mesma hierarquia. A grade se adapta ao espaço disponível e vira uma coluna no celular.</p><div className="ds-widget-grid">{[['Vagas abertas','12'],['Em entrevista','28'],['Contratações','4']].map(([label,value])=><WidgetGroup key={label}><span>{label}</span><strong className="ds-widget-number">{value}</strong><span className="ds-widget-caption">Indicador demonstrativo</span></WidgetGroup>)}</div></section>
 <section><h2>Espaçamentos e linhas de respiro</h2><WidgetGroup><div className="ds-widget-spacing">{[8,16,24,32].map(n=><div key={n}><i style={{width:n,height:n}}/><strong>{n} px</strong><span>{n===8?'Itens próximos':n===16?'Controles relacionados':n===24?'Interior dos grupos':'Entre seções'}</span></div>)}</div><WidgetDivider label="Uma mudança de assunto"/><p>Use a linha para separar conjuntos distintos. Dentro do mesmo assunto, prefira espaço em branco.</p></WidgetGroup></section>
 <section><h2>Sobreposições e grupos de foco</h2><div className="ds-widget-grid"><WidgetGroup><span className="ds-widget-caption">POP-UP</span><h3>Uma ação por vez</h3><p>Confirmações e formulários curtos. Bloqueia a página até a conclusão ou o fechamento.</p><ActionButton onClick={()=>setOverlay('modal')}>Abrir pop-up</ActionButton></WidgetGroup><WidgetGroup><span className="ds-widget-caption">GROUP FOCUS</span><h3>Próximo do contexto</h3><p>Opções rápidas junto ao controle que as abriu. Fecha ao sair, clicar fora ou pressionar Esc.</p><FocusPopover label="Ajustar visualização"><strong>Preferências da lista</strong><CheckboxField label="Exibir somente vagas ativas" checked={onlyActive} onChange={e=>setOnlyActive(e.target.checked)}/><span className="ds-widget-caption">{onlyActive?'Filtro de vagas ativas selecionado.':'Todas as vagas selecionadas.'}</span></FocusPopover></WidgetGroup><WidgetGroup><span className="ds-widget-caption">PAINEL LATERAL DIREITO</span><h3>Detalhes sem sair</h3><p>Painel flutuante com contexto adicional, rolagem própria e ação de fechar sempre acessível.</p><ActionButton variant="secondary" onClick={()=>setOverlay('drawer')}>Abrir detalhes</ActionButton></WidgetGroup></div></section>
 <section className="ds-sheet-section"><div><span className="ds-kicker">Exclusivo para a experiência mobile</span><h2>BottomSheet</h2><p>No celular, o grupo surge pela base da tela, respeita a área segura e permite rolar o conteúdo. No desktop, esta moldura demonstra o componente sem aplicá-lo ao layout.</p><ActionButton className="ds-sheet-mobile-trigger" onClick={()=>setOverlay('sheet')}>Abrir BottomSheet no celular</ActionButton><p className="ds-widget-caption">O painel à direita continua sendo a opção para detalhes no desktop.</p></div><div className="ds-sheet-preview" aria-label="Prévia ilustrativa do BottomSheet em uma tela de celular"><div className="ds-sheet-preview__context"><span>Prévia mobile</span><strong>Vagas da empresa</strong><div/><div/></div><div className="ds-sheet-preview__surface"><div className="jf-sheet-handle"/><h3>Opções da vaga</h3><p>Escolha o próximo passo.</p><ActionButton variant="secondary" onClick={()=>setOverlay('drawer')}>Visualizar detalhes</ActionButton><span className="ds-widget-caption">Prévia do componente · área segura inferior</span></div></div></section>
 <WidgetDialog open={overlay==='modal'} onClose={close} title="Salvar preferências" description="Exemplo de uma ação curta em um pop-up." footer={<><ActionButton variant="quiet" onClick={close}>Cancelar</ActionButton><ActionButton onClick={close}>Concluir exemplo</ActionButton></>}><TextField label="Nome da visualização" placeholder="Ex.: Vagas do time comercial"/><p className="ds-widget-caption">Demonstração visual. Nenhuma configuração será alterada.</p></WidgetDialog>
 <WidgetDialog open={overlay==='drawer'} onClose={close} kind="drawer" title="Detalhes da vaga" description="Informações adicionais no contexto da lista." footer={<ActionButton variant="secondary" onClick={close}>Fechar detalhes</ActionButton>}><StatusBadge tone="positive">Publicada</StatusBadge><h3>Analista de Customer Success</h3><p>Time de relacionamento · Híbrido</p><WidgetDivider label="Sobre a oportunidade"/><p>Acompanhe a experiência dos clientes, organize demandas e apoie o crescimento das contas.</p><WidgetGroup variant="outline"><strong>Próxima etapa</strong><p>Entrevista com a liderança.</p></WidgetGroup><WidgetDivider/><p className="ds-widget-caption">Exemplo demonstrativo. O painel possui rolagem própria quando o conteúdo é maior que a tela.</p></WidgetDialog>
 <WidgetDialog open={overlay==='sheet'} onClose={close} kind="sheet" title="Opções da vaga" description="Ações próximas ao alcance das mãos." footer={<ActionButton variant="quiet" onClick={close}>Fechar</ActionButton>}><p>Analista de Customer Success</p><ActionButton variant="secondary" onClick={()=>setOverlay('drawer')}>Visualizar detalhes</ActionButton></WidgetDialog>
 </section>;
}
