import { emptyJob, type Candidate, type Job, type JobSettings } from "./job-types";
const now = "2026-09-19T12:00:00.000Z";
export const seedJobs:Job[]=[
  {...emptyJob(),id:"job-customer-success",createdAt:now,updatedAt:now,status:"Publicada",title:"Analista de Customer Success",area:"Suporte",level:"Pleno",contractType:"CLT",modality:"Híbrido",state:"DF",city:"Brasília",summary:"Conduza a jornada de clientes e transforme necessidades em resultados sustentáveis.",responsibilities:["Acompanhar a carteira de clientes","Conduzir reuniões de sucesso","Mapear oportunidades de expansão"],requirements:["Experiência em atendimento B2B","Comunicação clara","Análise de indicadores"],softSkills:["Empatia","Organização"],benefits:["Plano de saúde","Vale-refeição"],teamDescription:"Time multidisciplinar orientado ao sucesso do cliente.",stages:[{id:"triagem",name:"Triagem",required:true},{id:"entrevista",name:"Entrevista",required:true},{id:"case",name:"Case prático",required:true},{id:"proposta",name:"Proposta",required:true}],lgpd:true,applicationDeadline:"2026-10-30",applicationsCount:42},
  {...emptyJob(),id:"job-dev-projetos",createdAt:now,updatedAt:now,status:"Publicada",title:"Desenvolvedor de Projetos",area:"Tecnologia",level:"Sênior",contractType:"PJ",modality:"Remoto",state:"SP",city:"São Paulo",summary:"Crie produtos digitais confiáveis e evolua nossa plataforma de recrutamento.",responsibilities:["Desenvolver aplicações web","Revisar arquitetura","Apoiar pessoas do time"],requirements:["TypeScript avançado","React","APIs REST"],tools:["React","TypeScript","PostgreSQL"],benefits:["Auxílio home office","Bônus"],stages:[{id:"triagem",name:"Triagem",required:true},{id:"tecnica",name:"Entrevista técnica",required:true},{id:"lideranca",name:"Liderança",required:true}],lgpd:true,applicationsCount:31},
  {...emptyJob(),id:"job-product-designer",createdAt:now,updatedAt:now,status:"Pausada",title:"Product Designer",area:"Design",level:"Pleno",contractType:"CLT",modality:"Híbrido",state:"SP",city:"São Paulo",summary:"Desenhe experiências simples para fluxos complexos de recrutamento.",applicationsCount:18}
];
export const seedCandidates:Candidate[]=[
 {id:"cand-1",organizationId:"org_jobforged_demo",jobId:"job-customer-success",createdAt:now,updatedAt:now,status:"Ativa",name:"Mariana Costa",email:"mariana.costa@email.com",skills:["CS","SaaS","CRM"],stage:"Entrevista",score:92,location:"Brasília, DF",resume:"curriculo-mariana.pdf",notes:"Boa comunicação e repertório B2B.",history:["Candidatura recebida","Avançou para Triagem","Avançou para Entrevista"]},
 {id:"cand-2",organizationId:"org_jobforged_demo",jobId:"job-customer-success",createdAt:now,updatedAt:now,status:"Ativa",name:"Lucas Ferreira",email:"lucas@email.com",skills:["Atendimento","Dados"],stage:"Triagem",score:81,location:"Goiânia, GO",resume:"curriculo-lucas.pdf",notes:"",history:["Candidatura recebida"]},
 {id:"cand-3",organizationId:"org_jobforged_demo",jobId:"job-customer-success",createdAt:now,updatedAt:now,status:"Ativa",name:"Ana Ribeiro",email:"ana@email.com",skills:["Customer Success","Inglês"],stage:"Case prático",score:87,location:"Curitiba, PR",resume:"curriculo-ana.pdf",notes:"Experiência internacional.",history:["Candidatura recebida","Triagem concluída","Entrevista concluída"]}
];
export const defaultSettings:JobSettings={aiScreening:false,advanceScore:80,rejectScore:45,highFitNotification:true,visibility:"Pública",acceptApplications:true,resumeRequired:true,coverLetter:false,anonymous:false,applicationLimit:0,positions:1,autoClose:false,notifications:["Nova candidatura","Candidato com alta aderência"],slug:"",metaDescription:"",shareTitle:"",questions:[],rules:[]};
