"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { useEffect,useMemo,useState } from "react";
import { Archive,BriefcaseBusiness,Copy,Eye,Grid2X2,List,MoreHorizontal,Pause,Play,Plus,Search,Trash2 } from "lucide-react";
import { ActionButton,EmptyState,StatusBadge } from "@/app/components/ui";
import { AdminPageHeader,AdminShell } from "@/app/components/admin/AdminModuleClient";
import type { AwaitedAdminContext } from "@/app/components/admin/admin-types";
import { getCompletion,jobService } from "./job-service";
import type { Job,JobStatus } from "./job-types";
import "./jobs.css";
const tone=(s:JobStatus)=>s==="Publicada"?"positive":s==="Pausada"?"warning":s==="Rascunho"?"neutral":s==="Arquivada"?"danger":"info";
export default function JobsListClient({context}:{context:AwaitedAdminContext}){
 const [jobs,setJobs]=useState<Job[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[status,setStatus]=useState("Todos"),[sort,setSort]=useState("recent"),[view,setView]=useState<"cards"|"list">("cards"),[menu,setMenu]=useState<string|null>(null),[notice,setNotice]=useState("");
 const load=()=>jobService.listJobs(context.organization.id).then(setJobs).finally(()=>setLoading(false)); useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>jobs.filter(j=>(status==="Todos"||j.status===status)&&`${j.title} ${j.area} ${j.city}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="title"?a.title.localeCompare(b.title):b.updatedAt.localeCompare(a.updatedAt)),[jobs,query,status,sort]);
 const change=async(j:Job,next:JobStatus)=>{await jobService.changeJobStatus(j.id,next);setNotice(`Status alterado para ${next.toLowerCase()}.`);setMenu(null);await load()};
 const duplicate=async(j:Job)=>{await jobService.duplicateJob(j.id);setNotice("Vaga duplicada como rascunho.");setMenu(null);await load()};
 const remove=async(j:Job)=>{if(confirm(`Excluir permanentemente “${j.title}”? Esta ação remove somente os dados simulados.`)){await jobService.deleteJob(j.id);setNotice("Vaga excluída.");await load()}};
 return <AdminShell module="vagas" context={context}><AdminPageHeader module="vagas" action={<a className="jf-action jf-action--primary" href="/app/vagas/nova"><Plus/>Criar vaga</a>}/>{notice&&<div className="jobs-toast" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
 <section className="jobs-overview"><article><BriefcaseBusiness/><span><strong>{jobs.length}</strong>Total de vagas</span></article><article><Play/><span><strong>{jobs.filter(j=>j.status==="Publicada").length}</strong>Publicadas</span></article><article><Pause/><span><strong>{jobs.filter(j=>j.status==="Pausada").length}</strong>Pausadas</span></article><article><span className="jobs-number">Σ</span><span><strong>{jobs.reduce((n,j)=>n+j.applicationsCount,0)}</strong>Candidaturas</span></article></section>
 <div className="jobs-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por título, área ou localização"/></label><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filtrar por status">{["Todos","Publicada","Rascunho","Pausada","Encerrada","Arquivada"].map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Ordenar vagas"><option value="recent">Mais recentes</option><option value="title">Título A–Z</option></select><div className="jobs-view"><button className={view==="cards"?"is-active":""} onClick={()=>setView("cards")} aria-label="Visualização em cards"><Grid2X2/></button><button className={view==="list"?"is-active":""} onClick={()=>setView("list")} aria-label="Visualização em lista"><List/></button></div></div>
 {loading?<div className="jobs-skeleton" aria-label="Carregando vagas">{[1,2,3].map(x=><i key={x}/>)}</div>:filtered.length===0?<EmptyState title="Nenhuma vaga encontrada" description={query?"Revise a busca ou remova os filtros aplicados.":"Crie a primeira vaga para iniciar o recrutamento."} action={<a className="jf-action jf-action--primary" href="/app/vagas/nova">Criar vaga</a>}/>:<div className={`jobs-collection is-${view}`}>{filtered.map(j=>{const q=getCompletion(j);return <article className="job-card" key={j.id}><header><div><StatusBadge tone={tone(j.status)}>{j.status}</StatusBadge><small>Atualizada em {new Date(j.updatedAt).toLocaleDateString("pt-BR")}</small></div><button onClick={()=>setMenu(menu===j.id?null:j.id)} aria-label={`Ações para ${j.title}`}><MoreHorizontal/></button>{menu===j.id&&<div className="job-menu"><a href={`/app/vagas/${j.id}`}><Eye/>Abrir painel</a><a href={`/app/vagas/${j.id}/editar`}><BriefcaseBusiness/>Editar</a><button onClick={()=>duplicate(j)}><Copy/>Duplicar</button><button onClick={()=>change(j,j.status==="Publicada"?"Pausada":"Publicada")}>{j.status==="Publicada"?<Pause/>:<Play/>}{j.status==="Publicada"?"Pausar":"Publicar"}</button><button onClick={()=>change(j,"Arquivada")}><Archive/>Arquivar</button><button className="danger" onClick={()=>remove(j)}><Trash2/>Excluir</button></div>}</header><a className="job-card-main" href={`/app/vagas/${j.id}`}><h2>{j.title||"Vaga sem título"}</h2><p>{j.area||"Área não definida"} · {j.level||"Nível não definido"}</p><div className="job-tags"><span>{j.modality||"Modalidade"}</span><span>{j.city?`${j.city}, ${j.state}`:"Local a definir"}</span><span>{j.contractType||"Contratação"}</span></div></a><footer><div><span>Candidaturas</span><strong>{j.applicationsCount}</strong></div><div><span>Completude</span><strong>{q.score}%</strong><i><b style={{width:`${q.score}%`}}/></i></div><div><span>Qualidade</span><strong>{q.quality}</strong></div></footer></article>})}</div>}</AdminShell>
}
