"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { useEffect,useMemo,useRef,useState } from "react";
import { ArrowLeft,ArrowRight,Check,Eye,GripVertical,Lightbulb,Monitor,Plus,Save,Smartphone,Tablet,Trash2,X } from "lucide-react";
import { ActionButton, FieldControl } from "@/app/components/ui";
import { AdminShell } from "@/app/components/admin/AdminModuleClient";
import type { AwaitedAdminContext } from "@/app/components/admin/admin-types";
import { emptyJob,type Job } from "./job-types";
import { getCompletion,jobService } from "./job-service";
import "./jobs.css";
const steps=["Identificação","Sobre a função","Perfil e diferenciais","Benefícios","Cultura e contexto","Processo seletivo"];
const areas=["Tecnologia","Marketing","Vendas","Financeiro","Recursos Humanos","Operações","Produto","Design","Jurídico","Administrativo","Engenharia","Dados","Suporte","Comercial","Logística","Outro"];
const states=["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"];
const benefits=["Vale-transporte","Vale-alimentação","Vale-refeição","Plano de saúde","Plano odontológico","Seguro de vida","Auxílio home office","Bônus","Participação nos lucros e resultados","Folga no aniversário","Benefício de atividades físicas","Auxílio-creche","Auxílio-educação","Stock options"];
const labels={Identificação:"Defina os dados que ajudam candidatos a reconhecer a oportunidade.","Sobre a função":"Explique impacto, rotina e requisitos com objetividade.","Perfil e diferenciais":"Registre conhecimentos e características que agregam valor.",Benefícios:"Apresente a proposta de valor oferecida pela organização.","Cultura e contexto":"Dê contexto sobre o time, desafios e forma de trabalho.","Processo seletivo":"Configure as etapas e os compromissos com candidatos."} as const;
function Field({label,children,required}:{label:string;children:React.ReactNode;required?:boolean}){return <FieldControl className="job-field" label={label} requiredLabel={required?"Obrigatório":undefined}>{children}</FieldControl>}
function Select({value,onChange,items,placeholder="Selecione"}:{value:string;onChange:(v:string)=>void;items:string[];placeholder?:string}){return <select value={value} onChange={e=>onChange(e.target.value)}><option value="">{placeholder}</option>{items.map(x=><option key={x}>{x}</option>)}</select>}
function DynamicList({title,items,onChange,min=0,placeholder}:{title:string;items:string[];onChange:(x:string[])=>void;min?:number;placeholder:string}){const [value,setValue]=useState("");const add=()=>{if(!value.trim())return;onChange([...items,value.trim()]);setValue("")};return <div className="job-dynamic"><div className="job-label"><span>{title}</span><small>{items.length}/{min} mín.</small></div>{items.map((x,i)=><div className="job-list-row" key={`${x}-${i}`}><GripVertical/><input value={x} onChange={e=>onChange(items.map((v,n)=>n===i?e.target.value:v))}/><button type="button" onClick={()=>onChange(items.filter((_,n)=>n!==i))} aria-label={`Remover ${x}`}><Trash2/></button></div>)}<div className="job-add-row"><input value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();add()}}} placeholder={placeholder}/><ActionButton type="button" variant="secondary" icon={<Plus/>} onClick={add}>Adicionar</ActionButton></div></div>}
export default function JobWizardClient({context,jobId}:{context:AwaitedAdminContext;jobId?:string}){
 const [job,setJob]=useState<Job>(()=>emptyJob(context.organization.id)),[step,setStep]=useState(0),[saveState,setSaveState]=useState("Alterações pendentes"),[preview,setPreview]=useState(false),[device,setDevice]=useState<"desktop"|"tablet"|"mobile">("desktop"),[notice,setNotice]=useState("");const ready=useRef(false);
 useEffect(()=>{(async()=>{const found=jobId?await jobService.getJobById(jobId):jobService.getDraft();const next=found?.organizationId===context.organization.id?found:emptyJob(context.organization.id);setJob(next);setStep(next.currentStep||0);ready.current=true})()},[jobId]);
 useEffect(()=>{if(!ready.current)return;setSaveState("Alterações pendentes");const t=setTimeout(async()=>{setSaveState("Salvando…");try{const current={...job,currentStep:step};if(current.id)setJob(await jobService.updateJob(current.id,current));else jobService.saveDraft(current);setSaveState("Salvo agora")}catch{setSaveState("Não foi possível salvar")}},700);return()=>clearTimeout(t)},[job,step]);
 const quality=useMemo(()=>getCompletion(job),[job]);const set=<K extends keyof Job>(key:K,value:Job[K])=>setJob(x=>({...x,[key]:value}));
 const openPreview=()=>{if(job.id)void jobService.updateJob(job.id,job);else jobService.saveDraft({...job,currentStep:step});setPreview(true)};
 const persist=async(status:"Rascunho"|"Publicada")=>{if(status==="Publicada"&&!quality.canPublish){setNotice("Complete os campos obrigatórios antes de publicar.");return}const saved=job.id?await jobService.updateJob(job.id,{...job,status}):await jobService.createJob({...job,status});jobService.clearDraft();setJob(saved);setNotice(status==="Publicada"?"Vaga publicada com sucesso.":"Rascunho salvo com sucesso.");history.replaceState(null,"",`/app/vagas/${saved.id}/editar`)};
 const clear=()=>{if(confirm("Limpar todos os dados preenchidos nesta vaga?")){jobService.clearDraft();setJob(emptyJob(context.organization.id));setStep(0)}};
 const stage=<>{step===0&&<div className="job-form-grid"><Field label="Título da vaga" required><input value={job.title} onChange={e=>set("title",e.target.value)} placeholder="Ex.: Analista de Customer Success"/></Field><Field label="Área ou departamento" required><Select value={job.area} onChange={v=>set("area",v)} items={areas}/></Field><Field label="Nível" required><Select value={job.level} onChange={v=>set("level",v)} items={["Estágio","Trainee","Júnior","Pleno","Sênior","Especialista","Coordenador","Gerente","Diretor"]}/></Field><Field label="Tipo de contratação" required><Select value={job.contractType} onChange={v=>set("contractType",v)} items={["CLT","PJ","Estágio","Temporário","Freelancer","Aprendiz"]}/></Field><Field label="Modalidade" required><Select value={job.modality} onChange={v=>set("modality",v)} items={["Presencial","Híbrido","Remoto"]}/></Field><Field label="País" required><input value={job.country} onChange={e=>set("country",e.target.value)} placeholder="Brasil"/></Field><Field label="Estado" required><Select value={job.state} onChange={v=>{set("state",v);set("city","")}} items={states}/></Field><Field label="Cidade" required><input value={job.city} onChange={e=>set("city",e.target.value)} disabled={!job.state} placeholder={job.state?"Digite uma cidade compatível":"Selecione o estado primeiro"}/></Field></div>}
 {step===1&&<><Field label="Resumo da vaga" required><textarea maxLength={500} value={job.summary} onChange={e=>set("summary",e.target.value)} placeholder="Apresente o propósito, o impacto e o contexto da posição."/><small>{job.summary.length}/500 caracteres</small></Field><DynamicList title="Principais responsabilidades" items={job.responsibilities} onChange={v=>set("responsibilities",v)} min={3} placeholder="Descreva uma responsabilidade"/><DynamicList title="Requisitos obrigatórios" items={job.requirements} onChange={v=>set("requirements",v)} min={3} placeholder="Descreva um requisito"/><div className="job-form-grid"><Field label="Experiência mínima"><input value={job.experience} onChange={e=>set("experience",e.target.value)} placeholder="Ex.: 3 anos"/></Field><Field label="Carga horária semanal"><input value={job.weeklyHours} onChange={e=>set("weeklyHours",e.target.value)} placeholder="Ex.: 40 horas"/></Field><Field label="Horário de trabalho"><input value={job.schedule} onChange={e=>set("schedule",e.target.value)} placeholder="Ex.: Flexível, entre 8h e 18h"/></Field><Field label="Moeda"><Select value={job.currency} onChange={v=>set("currency",v)} items={["BRL","USD","EUR"]}/></Field><Field label="Faixa salarial mínima"><input type="number" value={job.salaryMin} onChange={e=>set("salaryMin",e.target.value)} placeholder="0"/></Field><Field label="Faixa salarial máxima"><input type="number" value={job.salaryMax} onChange={e=>set("salaryMax",e.target.value)} placeholder="0"/></Field></div><label className="job-check"><input type="checkbox" checked={job.salaryConfidential} onChange={e=>set("salaryConfidential",e.target.checked)}/><span>Manter faixa salarial confidencial</span></label></>}
 {step===2&&<><DynamicList title="Soft skills" items={job.softSkills} onChange={v=>set("softSkills",v)} placeholder="Ex.: comunicação clara"/><DynamicList title="Diferenciais" items={job.differentiators} onChange={v=>set("differentiators",v)} placeholder="Ex.: experiência internacional"/><DynamicList title="Certificações desejadas" items={job.certifications} onChange={v=>set("certifications",v)} placeholder="Ex.: AWS Solutions Architect"/><Field label="Formação mínima"><Select value={job.education} onChange={v=>set("education",v)} items={["Ensino Médio","Técnico","Graduação","Pós-graduação","MBA","Mestrado","Doutorado"]}/></Field><div className="job-dynamic"><div className="job-label"><span>Idiomas e proficiência</span><button onClick={()=>set("languages",[...job.languages,{language:"",level:""}])}><Plus/>Adicionar idioma</button></div>{job.languages.map((l,i)=><div className="job-list-row" key={i}><input value={l.language} onChange={e=>set("languages",job.languages.map((x,n)=>n===i?{...x,language:e.target.value}:x))} placeholder="Idioma"/><Select value={l.level} onChange={v=>set("languages",job.languages.map((x,n)=>n===i?{...x,level:v}:x))} items={["Básico","Intermediário","Avançado","Fluente","Nativo"]}/><button onClick={()=>set("languages",job.languages.filter((_,n)=>n!==i))}><Trash2/></button></div>)}</div></>}
 {step===3&&<><div className="job-benefits">{benefits.map(b=><label key={b} className={job.benefits.includes(b)?"is-selected":""}><input type="checkbox" checked={job.benefits.includes(b)} onChange={e=>set("benefits",e.target.checked?[...job.benefits,b]:job.benefits.filter(x=>x!==b))}/><Check/>{b}</label>)}</div><Field label="Outros benefícios"><textarea value={job.additionalBenefits} onChange={e=>set("additionalBenefits",e.target.value)} placeholder="Descreva benefícios próprios da organização."/></Field><Field label="Plano de carreira"><textarea value={job.careerPlan} onChange={e=>set("careerPlan",e.target.value)} placeholder="Explique caminhos de desenvolvimento e crescimento."/></Field><label className="job-check"><input type="checkbox" checked={job.performanceReviews} onChange={e=>set("performanceReviews",e.target.checked)}/><span>A organização realiza avaliações periódicas de desempenho</span></label><label className="job-check"><input type="checkbox" checked={job.promotionPossible} onChange={e=>set("promotionPossible",e.target.checked)}/><span>Existe possibilidade de promoção</span></label></>}
 {step===4&&<><Field label="Descrição do time"><textarea value={job.teamDescription} onChange={e=>set("teamDescription",e.target.value)} placeholder="Conte como o time trabalha e se organiza."/></Field><div className="job-form-grid"><Field label="Reporta-se a"><input value={job.reportsTo} onChange={e=>set("reportsTo",e.target.value)} placeholder="Ex.: Gerente de Produto"/></Field><Field label="Tamanho da equipe"><input value={job.teamSize} onChange={e=>set("teamSize",e.target.value)} placeholder="Ex.: 8 pessoas"/></Field><Field label="Metodologia"><Select value={job.methodology} onChange={v=>set("methodology",v)} items={["Scrum","Kanban","XP","Waterfall","SAFe","Lean","Outro"]}/></Field><Field label="Nível de autonomia"><Select value={job.autonomy} onChange={v=>set("autonomy",v)} items={["Baixa — supervisão frequente","Média — autonomia com alinhamentos","Alta — autonomia e responsabilidade sobre entregas"]}/></Field></div><DynamicList title="Tecnologias e ferramentas" items={job.tools} onChange={v=>set("tools",v)} placeholder="Ex.: HubSpot"/><Field label="Principais desafios"><textarea value={job.challenges} onChange={e=>set("challenges",e.target.value)} placeholder="Quais desafios essa pessoa encontrará?"/></Field><div className="job-form-grid"><Field label="Motivo da abertura"><input value={job.openingReason} onChange={e=>set("openingReason",e.target.value)} placeholder="Ex.: expansão do time"/></Field><Field label="Estrutura hierárquica"><input value={job.hierarchy} onChange={e=>set("hierarchy",e.target.value)} placeholder="Ex.: Analista → Coordenação → Diretoria"/></Field></div></>}
 {step===5&&<><div className="job-dynamic"><div className="job-label"><span>Etapas do processo</span><button onClick={()=>set("stages",[...job.stages,{id:`stage-${Date.now()}`,name:"Nova etapa",required:false}])}><Plus/>Adicionar etapa</button></div>{job.stages.map((s,i)=><div className="job-list-row" key={s.id}><GripVertical/><input value={s.name} onChange={e=>set("stages",job.stages.map((x,n)=>n===i?{...x,name:e.target.value}:x))}/><label><input type="checkbox" checked={s.required} onChange={e=>set("stages",job.stages.map((x,n)=>n===i?{...x,required:e.target.checked}:x))}/> Obrigatória</label><button onClick={()=>set("stages",job.stages.filter((_,n)=>n!==i))}><Trash2/></button></div>)}</div><label className="job-check"><input type="checkbox" checked={job.technicalTest} onChange={e=>set("technicalTest",e.target.checked)}/><span>Este processo inclui teste técnico</span></label><div className="job-benefits">{["Técnica","Comportamental","Cultural","Case prático","Entrevista com liderança","Entrevista final"].map(x=><label className={job.interviewTypes.includes(x)?"is-selected":""} key={x}><input type="checkbox" checked={job.interviewTypes.includes(x)} onChange={e=>set("interviewTypes",e.target.checked?[...job.interviewTypes,x]:job.interviewTypes.filter(v=>v!==x))}/><Check/>{x}</label>)}</div><div className="job-form-grid"><Field label="Prazo para candidaturas"><input type="date" value={job.applicationDeadline} onChange={e=>set("applicationDeadline",e.target.value)}/></Field><Field label="Prazo esperado de retorno"><input value={job.responseSla} onChange={e=>set("responseSla",e.target.value)} placeholder="Ex.: até 5 dias úteis"/></Field></div><label className="job-check"><input type="checkbox" checked={job.lgpd} onChange={e=>set("lgpd",e.target.checked)}/><span>Confirmo a conformidade deste processo com a LGPD <b>Obrigatório</b></span></label></>}</>;
 return <AdminShell module="vagas" context={context}><div className="job-wizard-head"><a href="/app/vagas"><ArrowLeft/>Voltar para vagas</a><div><span>{jobId?"Editar vaga":"Nova vaga"}</span><h1>{job.title||"Crie uma oportunidade clara e atrativa"}</h1></div><div><span className={`save-state ${saveState.includes("Não")?"is-error":""}`}><Save/>{saveState}</span><ActionButton variant="secondary" onClick={clear}>Limpar</ActionButton><ActionButton variant="secondary" icon={<Eye/>} onClick={openPreview}>Modo candidato</ActionButton></div></div>{notice&&<div className="jobs-toast">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
 <div className="job-wizard"><aside className="job-steps">{steps.map((s,i)=><button className={step===i?"is-active":i<step?"is-done":""} onClick={()=>setStep(i)} key={s}><i>{i<step?<Check/>:i+1}</i><span>{s}</span></button>)}</aside><section className="job-stage"><header><small>Etapa {step+1} de {steps.length}</small><h2>{steps[step]}</h2><p>{labels[steps[step] as keyof typeof labels]}</p></header>{stage}<footer><ActionButton variant="secondary" disabled={step===0} onClick={()=>setStep(s=>s-1)} icon={<ArrowLeft/>}>Anterior</ActionButton><div><ActionButton variant="quiet" onClick={()=>persist("Rascunho")}>Salvar rascunho</ActionButton>{step<5?<ActionButton onClick={()=>setStep(s=>s+1)}>Continuar <ArrowRight/></ActionButton>:<ActionButton disabled={!quality.canPublish} onClick={()=>persist("Publicada")}>Publicar vaga</ActionButton>}</div></footer></section><aside className="job-quality"><span>Qualidade da vaga</span><strong>{quality.quality}</strong><div className="quality-ring" style={{"--value":`${quality.score*3.6}deg`} as React.CSSProperties}><b>{quality.score}%</b></div><p>{quality.requiredDone} de {quality.requiredTotal} campos obrigatórios concluídos</p><i><b style={{width:`${quality.score}%`}}/></i><div><Lightbulb/><span><b>Próxima melhoria</b>{quality.score<55?"Preencha resumo, responsabilidades e requisitos.":quality.score<85?"Detalhe benefícios, cultura e processo.":"A vaga está pronta para atrair candidatos."}</span></div></aside></div>
 {preview&&<div className="job-preview-modal" role="dialog" aria-modal="true" aria-label="Modo candidato"><header><div><strong>Modo candidato</strong><span>Prévia com os dados atuais</span></div><div className="device-switch"><button className={device==="desktop"?"is-active":""} onClick={()=>setDevice("desktop")}><Monitor/></button><button className={device==="tablet"?"is-active":""} onClick={()=>setDevice("tablet")}><Tablet/></button><button className={device==="mobile"?"is-active":""} onClick={()=>setDevice("mobile")}><Smartphone/></button></div><button onClick={()=>setPreview(false)} aria-label="Fechar prévia"><X/></button></header><div className={`candidate-frame is-${device}`}><div className="candidate-page"><header><img src={context.organization.logo} alt=""/><span>{context.organization.name}</span></header><main><small>{job.area||"Área"}</small><h1>{job.title||"Título da vaga"}</h1><p>{[job.level,job.contractType,job.modality,job.city&&`${job.city}, ${job.state}`].filter(Boolean).join(" · ")}</p>{!job.salaryConfidential&&job.salaryMin&&<b>{job.currency} {job.salaryMin} – {job.salaryMax}</b>}<button>Quero me candidatar</button><section><h2>Sobre a oportunidade</h2><p>{job.summary||"O resumo da vaga aparecerá aqui."}</p></section>{job.responsibilities.length>0&&<section><h2>Responsabilidades</h2><ul>{job.responsibilities.map(x=><li key={x}>{x}</li>)}</ul></section>}{job.requirements.length>0&&<section><h2>Requisitos</h2><ul>{job.requirements.map(x=><li key={x}>{x}</li>)}</ul></section>}{job.benefits.length>0&&<section><h2>Benefícios</h2><div className="candidate-tags">{job.benefits.map(x=><span key={x}>{x}</span>)}</div></section>}{job.teamDescription&&<section><h2>Time e cultura</h2><p>{job.teamDescription}</p></section>}{job.stages.length>0&&<section><h2>Processo seletivo</h2><ol>{job.stages.map(x=><li key={x.id}>{x.name}</li>)}</ol></section>}</main></div></div></div>}</AdminShell>
}
