"use client";

/* eslint-disable react-hooks/set-state-in-effect */

import { useEffect, useState, type ReactNode } from "react";
import { Bell, BriefcaseBusiness, CalendarDays, ChartNoAxesCombined, Check, ChevronDown, CircleDollarSign, Download, FileText, House, LayoutDashboard, ListFilter, LogOut, Menu, MoreHorizontal, Palette, PanelLeftClose, PanelLeftOpen, Plus, Search, Settings2, ShieldCheck, SlidersHorizontal, UserRound, UsersRound, WalletCards, X } from "lucide-react";
import { ActionButton, DataTable, StatusBadge, ThemeSelector, ToggleSwitch } from "@/app/components/ui";
import { moduleCopy, type AdminModuleId } from "./admin-data";
import type { AwaitedAdminContext } from "./admin-types";

const nav = [
  ["Home","/app/home",House],["Dashboards","/app/dashboards",LayoutDashboard],["Vagas","/app/vagas",BriefcaseBusiness],["Candidaturas","/app/candidaturas",UsersRound],["Agenda","/app/agenda",CalendarDays],["Personalização","/app/personalizacao",Palette],["Administradores","/app/administradores",ShieldCheck],["Financeiro","/app/financeiro",WalletCards],["Configurações","/app/configuracoes",Settings2],
] as const;

export function AdminShell({ module, context, children }: { module: AdminModuleId; context: AwaitedAdminContext; children: ReactNode }) {
  const [collapsed,setCollapsed]=useState(false); const [menu,setMenu]=useState(false); const [theme,setTheme]=useState<"light"|"dark">("light");
  useEffect(()=>{const saved=document.documentElement.dataset.theme;if(saved==="dark"||saved==="light")setTheme(saved)},[]);
  const changeTheme=(next:"light"|"dark")=>{setTheme(next);document.documentElement.dataset.theme=next;document.documentElement.style.colorScheme=next;localStorage.setItem("jobforged-theme",next)};
  return <main className={`admin-shell ${collapsed?"is-collapsed":""}`} data-theme={theme}>
    <aside className={`admin-sidebar ${menu?"is-open":""}`}><div className="admin-brand"><span><img src={context.organization.logo} alt=""/><strong>{context.organization.shortName}</strong></span><button onClick={()=>setCollapsed(v=>!v)} aria-label={collapsed?"Expandir menu":"Recolher menu"}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</button><button className="admin-close" onClick={()=>setMenu(false)} aria-label="Fechar menu"><X/></button></div><nav>{nav.map(([label,href,Icon])=><a key={href} href={href} className={`/app/${module}`===href?"is-active":""} aria-current={`/app/${module}`===href?"page":undefined}><Icon/><span>{label}</span></a>)}</nav><div className="admin-user"><a href="/app/minha-conta"><span>{context.user.initials}</span><span><strong>{context.user.name}</strong><small>{context.user.role}</small></span></a><button aria-label="Sair da conta" title="Sair da conta"><LogOut/></button></div></aside>
    {menu&&<button className="admin-scrim" onClick={()=>setMenu(false)} aria-label="Fechar menu"/>}
    <section className="admin-workspace"><header className="admin-topbar"><button className="admin-menu" onClick={()=>setMenu(true)} aria-label="Abrir menu"><Menu/></button><div className="admin-org"><img src={context.organization.logo} alt=""/><span><small>Organização ativa</small><strong>{context.organization.name}</strong></span></div><div><ThemeSelector theme={theme} onChange={changeTheme}/><button className="admin-notice" aria-label="Notificações"><Bell/><i/></button></div></header><div className="admin-content">{children}</div></section>
  </main>
}

export function AdminPageHeader({ module, action }: { module: AdminModuleId; action?: ReactNode }) { const copy=moduleCopy[module]; return <header className="admin-page-head"><div><span>Painel / {copy.title}</span><h1>{copy.title}</h1><p>{copy.description}</p></div>{action}</header> }
const PageHeader = AdminPageHeader;
function Toolbar({ search="Pesquisar", children }: { search?:string; children?:ReactNode }) { return <div className="admin-toolbar"><label><Search/><input placeholder={search}/></label><div>{children}<ActionButton variant="secondary" icon={<ListFilter/>}>Filtros</ActionButton></div></div> }
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <article className="admin-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function tone(status:string){return status==="Publicado"||status==="Publicada"||status==="Ativo"||status==="Pago"?"positive":status.includes("Pendente")||status==="Pausada"?"warning":status==="Rascunho"?"neutral":"info" as const}

function Dashboards({c}:{c:AwaitedAdminContext}){return <><PageHeader module="dashboards" action={<div className="admin-actions"><ActionButton variant="secondary" icon={<CalendarDays/>}>Últimos 30 dias</ActionButton><ActionButton variant="secondary" icon={<Download/>}>Exportar dados</ActionButton></div>}/><div className="admin-metrics"><Metric label="Vagas criadas" value="24" detail="+14% no período"/><Metric label="Visualizações" value="8.420" detail="+21% no período"/><Metric label="Candidaturas" value="486" detail="5,8% de conversão"/><Metric label="Tempo médio" value="18 dias" detail="3 dias mais rápido"/></div><div className="admin-chart-grid"><section className="admin-card admin-chart"><header><div><h2>Candidaturas e visualizações</h2><p>Evolução semanal do interesse pelas vagas</p></div><StatusBadge tone="positive">+18,4%</StatusBadge></header><div className="admin-line-chart" aria-label="Gráfico demonstrativo"><i/><i/><i/><i/><i/><i/><svg viewBox="0 0 600 160" preserveAspectRatio="none"><polyline points="0,130 100,105 200,117 300,70 400,82 500,34 600,45"/><polyline className="is-secondary" points="0,148 100,137 200,130 300,118 400,104 500,91 600,76"/></svg></div></section><section className="admin-card"><header><div><h2>Funil de recrutamento</h2><p>Conversão entre as principais etapas</p></div></header><div className="admin-funnel">{[["Visualizações","8.420",100],["Candidaturas","486",72],["Triagem","218",51],["Entrevistas","94",34],["Contratações","17",18]].map(([l,v,w])=><div key={String(l)}><span>{l}</span><i style={{width:`${w}%`}}/><strong>{v}</strong></div>)}</div></section></div><section className="admin-card"><header><div><h2>Vagas com melhor desempenho</h2><p>Volume, qualidade e conversão no período</p></div></header><DataTable label="Desempenho das vagas" headers={["Vaga","Área","Candidaturas","Qualidade","Status"]}>{c.vacancies.slice(0,3).map(v=><tr key={v.id}><td><b>{v.title}</b></td><td>{v.area}</td><td>{v.applications}</td><td>{v.quality}%</td><td><StatusBadge tone={tone(v.status)}>{v.status}</StatusBadge></td></tr>)}</DataTable></section></>}

function Vacancies({c}:{c:AwaitedAdminContext}){return <><PageHeader module="vagas" action={<ActionButton icon={<Plus/>}>Criar vaga</ActionButton>}/><Toolbar search="Buscar por título, área ou local"><ActionButton variant="quiet">Todas</ActionButton></Toolbar><section className="admin-card"><DataTable label="Lista de vagas" headers={["Vaga","Área e modelo","Status","Candidaturas","Qualidade","Ações"]}>{c.vacancies.map(v=><tr key={v.id}><td><b>{v.title}</b><small>Atualizada recentemente</small></td><td>{v.area}<small>{v.model}</small></td><td><StatusBadge tone={tone(v.status)}>{v.status}</StatusBadge></td><td>{v.applications}</td><td><span className="admin-quality"><i style={{width:`${v.quality}%`}}/>{v.quality}%</span></td><td><button className="admin-icon" aria-label={`Ações para ${v.title}`}><MoreHorizontal/></button></td></tr>)}</DataTable></section></>}

function Applications({c}:{c:AwaitedAdminContext}){const [view,setView]=useState<"list"|"kanban">("kanban");return <><PageHeader module="candidaturas"/><Toolbar search="Buscar candidato, vaga ou etapa"><div className="admin-segment"><button className={view==="list"?"is-active":""} onClick={()=>setView("list")}>Lista</button><button className={view==="kanban"?"is-active":""} onClick={()=>setView("kanban")}>Kanban</button></div></Toolbar>{view==="list"?<section className="admin-card"><DataTable label="Candidaturas" headers={["Candidato","Vaga","Etapa","Fit","Recebida"]}>{c.candidates.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.vacancy}</td><td><StatusBadge tone="info">{x.stage}</StatusBadge></td><td>{x.score}%</td><td>{x.applied}</td></tr>)}</DataTable></section>:<div className="admin-kanban">{["Novos","Triagem","Entrevista","Avaliação","Proposta"].map(stage=><section key={stage}><header><strong>{stage}</strong><span>{c.candidates.filter(x=>x.stage===stage).length}</span></header>{c.candidates.filter(x=>x.stage===stage).map(x=><article key={x.id}><div><span>{x.name.split(" ").map(n=>n[0]).join("").slice(0,2)}</span><b>{x.name}</b></div><p>{x.vacancy}</p><footer><StatusBadge tone="info">Fit {x.score}%</StatusBadge><small>{x.applied}</small></footer></article>)}{!c.candidates.some(x=>x.stage===stage)&&<div className="admin-column-empty">Nenhuma candidatura</div>}</section>)}</div>}</>}

function Agenda(){return <><PageHeader module="agenda" action={<ActionButton icon={<Plus/>}>Novo compromisso</ActionButton>}/><div className="admin-agenda"><section className="admin-card admin-calendar"><header><button aria-label="Mês anterior">‹</button><h2>Setembro de 2026</h2><button aria-label="Próximo mês">›</button></header><div className="admin-calendar-grid">{["D","S","T","Q","Q","S","S"].map((d,i)=><b key={i}>{d}</b>)}{Array.from({length:35},(_,i)=><button key={i} className={i===18?"is-selected":i===20||i===23?"has-event":""}>{i<3?29+i:i-2}</button>)}</div></section><section className="admin-card admin-events"><header><div><h2>Próximos eventos</h2><p>Entrevistas e compromissos confirmados</p></div></header>{[["09:30","Entrevista · Mariana Costa","Customer Success"],["14:00","Avaliação técnica · Lucas Ferreira","Desenvolvedor de Projetos"],["16:30","Alinhamento com recrutadores","Equipe administrativa"]].map(e=><article key={e[0]}><strong>{e[0]}</strong><div><b>{e[1]}</b><span>{e[2]}</span></div><StatusBadge tone="positive">Confirmado</StatusBadge></article>)}</section></div></>}

function Personalization(){return <><PageHeader module="personalizacao" action={<ActionButton>Salvar alterações</ActionButton>}/><div className="admin-settings-grid"><section className="admin-card admin-form"><header><div><h2>Identidade da organização</h2><p>Elementos aplicados ao painel e ao portal de vagas</p></div></header><label>Logo principal<div className="admin-upload"><img src="/brand/jobforged-symbol.svg" alt="Prévia da logo"/><span><b>Logo da organização</b><small>SVG ou PNG · até 2 MB</small></span><ActionButton variant="secondary">Substituir</ActionButton></div></label><div className="admin-field-row"><label>Cor principal<input type="color" defaultValue="#20b2aa"/></label><label>Cor secundária<input type="color" defaultValue="#4169e1"/></label></div><label>Nome exibido<input defaultValue="Inside Forge Tecnologia"/></label><label>Domínio do portal<input defaultValue="jobs.insideforge.com.br"/></label></section><section className="admin-card admin-brand-preview"><header><div><h2>Pré-visualização</h2><p>Resultado nos temas claro e escuro</p></div></header><div><aside><img src="/brand/jobforged-symbol.svg" alt=""/><i/><i/><i/></aside><main><span>Oportunidades</span><h3>Trabalhe com a gente.</h3><p>Encontre uma vaga que combina com o seu próximo passo.</p><button>Ver vagas abertas</button></main></div><ActionButton variant="quiet">Restaurar padrões</ActionButton></section></div></>}

function Administrators({c}:{c:AwaitedAdminContext}){return <><PageHeader module="administradores" action={<ActionButton icon={<Plus/>}>Convidar administrador</ActionButton>}/><Toolbar search="Buscar por nome, e-mail ou função"/><section className="admin-card"><DataTable label="Equipe administrativa" headers={["Pessoa","Função","Status","Último acesso","Vagas atribuídas","Ações"]}>{c.team.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.email}</small></td><td>{x.role}</td><td><StatusBadge tone={tone(x.status)}>{x.status}</StatusBadge></td><td>{x.access}</td><td>{x.vacancies}</td><td><button className="admin-icon" aria-label={`Ações para ${x.name}`}><MoreHorizontal/></button></td></tr>)}</DataTable></section></>}

function Finance({c}:{c:AwaitedAdminContext}){return <><PageHeader module="financeiro"/><div className="admin-finance-summary"><section><span>Plano atual</span><strong>Profissional</strong><small>Cobrança mensal</small></section><section><span>Próximo vencimento</span><strong>10 out 2026</strong><small>Pagamento automático</small></section><section><span>Consumo de vagas</span><strong>8 de 20</strong><i><b style={{width:"40%"}}/></i></section></div><section className="admin-card"><header><div><h2>Faturas</h2><p>Histórico de cobranças da organização</p></div><ActionButton variant="secondary" icon={<FileText/>}>Ver contrato</ActionButton></header><DataTable label="Faturas" headers={["Referência","Vencimento","Valor","Status","Documento"]}>{c.invoices.map(x=><tr key={x.id}><td><b>{x.reference}</b></td><td>{x.due}</td><td>{x.amount}</td><td><StatusBadge tone="positive">{x.status}</StatusBadge></td><td><ActionButton variant="quiet" icon={<Download/>}>Baixar</ActionButton></td></tr>)}</DataTable></section></>}

function Settings(){const [preferences,setPreferences]=useState([true,false,true]);const items=[["Notificar novas candidaturas","Avisar administradores responsáveis"],["Exigir currículo","Solicitar arquivo antes de concluir a candidatura"],["Confirmação de entrevista","Enviar lembrete automático ao candidato"]];return <><PageHeader module="configuracoes" action={<ActionButton>Salvar alterações</ActionButton>}/><div className="admin-settings-grid"><section className="admin-card admin-form"><header><div><h2>Dados da organização</h2><p>Informações usadas em documentos e comunicações</p></div></header><label>Razão social<input defaultValue="Inside Forge Tecnologia Ltda."/></label><div className="admin-field-row"><label>CNPJ<input defaultValue="12.345.678/0001-90"/></label><label>Telefone<input defaultValue="(61) 99163-0130"/></label></div><label>E-mail administrativo<input defaultValue="contato@insideforge.com.br"/></label><label>Endereço<textarea defaultValue="Brasília, Distrito Federal"/></label></section><section className="admin-card admin-preferences"><header><div><h2>Preferências do recrutamento</h2><p>Comportamentos padrão para novos processos</p></div></header><div className="admin-toggle-list">{items.map((x,i)=><ToggleSwitch key={x[0]} label={x[0]} description={x[1]} checked={preferences[i]} onCheckedChange={(checked)=>setPreferences(current=>current.map((value,index)=>index===i?checked:value))}/>)}</div><div className="admin-integration"><SlidersHorizontal/><div><b>Integrações</b><span>Calendários e automações serão configurados aqui.</span></div><StatusBadge>Em preparação</StatusBadge></div></section></div></>}

function Account({c}:{c:AwaitedAdminContext}){return <><PageHeader module="minha-conta" action={<ActionButton>Salvar perfil</ActionButton>}/><div className="admin-account"><section className="admin-card admin-profile-card"><span>{c.user.initials}</span><h2>{c.user.fullName}</h2><p>{c.user.email}</p><StatusBadge tone="positive">{c.user.role}</StatusBadge><hr/><a href="#dados">Dados pessoais</a><a href="#seguranca">Segurança</a><a href="#acessos">Sessões e acessos</a><button><LogOut/>Sair da conta</button></section><section className="admin-card admin-form" id="dados"><header><div><h2>Dados pessoais</h2><p>Informações vinculadas ao seu acesso</p></div></header><div className="admin-field-row"><label>Nome completo<input defaultValue={c.user.fullName}/></label><label>Cargo<input defaultValue="Fundador"/></label></div><label>E-mail<input defaultValue={c.user.email}/></label><label>Telefone<input defaultValue={c.user.phone}/></label><div className="admin-access-box"><ShieldCheck/><div><b>Organização atual</b><span>{c.organization.name} · {c.user.role}</span></div></div><header id="seguranca"><div><h2>Segurança</h2><p>Senha, sessões e dispositivos conectados</p></div><ActionButton variant="secondary">Alterar senha</ActionButton></header><div className="admin-session"><div><b>Chrome no Windows</b><span>Brasília, Brasil · sessão atual</span></div><StatusBadge tone="positive">Ativa</StatusBadge></div></section></div></>}

export default function AdminModuleClient({module,context}:{module:AdminModuleId;context:AwaitedAdminContext}){let content:ReactNode;if(module==="dashboards")content=<Dashboards c={context}/>;else if(module==="vagas")content=<Vacancies c={context}/>;else if(module==="candidaturas")content=<Applications c={context}/>;else if(module==="agenda")content=<Agenda/>;else if(module==="personalizacao")content=<Personalization/>;else if(module==="administradores")content=<Administrators c={context}/>;else if(module==="financeiro")content=<Finance c={context}/>;else if(module==="configuracoes")content=<Settings/>;else content=<Account c={context}/>;return <AdminShell module={module} context={context}>{content}</AdminShell>}
